name: ownerwaroengsederhana
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.2.1
  country_picker: ^2.0.26
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  file_picker: ^8.0.0+1
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5
  badges: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  firebase_app_check: ^0.2.2+7



dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/WS.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

